services:
  backend:
    image: backend
    container_name: mern-backend
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    networks:
      - mern-net

  frontend:
    image: frontend
    container_name: mern-frontend
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge
